dist: xenial
language: php

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env: SETUP=lowest

cache:
  directories:
    - $HOME/.composer/cache

before_script: cd server

before_install:
  - composer self-update
  - composer install --no-interaction

install:
  - composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

script: vendor/bin/phpunit
